curl --location 'https://content-summarizer-api-production.up.railway.app/api/v1/s3/upload-json-theme' \
--header 'Content-Type: application/json' \
--data '{
  "key": "tokyo-neon-night",
  "label": "Tokyo Neon Night",
  "summary": {
    "modalBackground": "#1A1B26",
    "textColor": "#C0CAF5",
    "headerStart": "#24283B",
    "headerEnd": "#15161E",
    "headerText": "#F7768E",
    "inputBackground": "#15161E",
    "inputBorder": "#414868",
    "primaryStart": "#F7768E",
    "primaryEnd": "#BB9AF7",
    "summaryPanelBackground": "#24283B",
    "summaryPanelBorder": "#7AA2F7",
    "summaryTitleColor": "#7DCFFF",
    "summaryMarkdownText": "#A9B1D6",
    "summaryMarkdownAccent": "#F7768E"
  },
  "explain": {
    "panelBackground": "#24283B",
    "borderColor": "#BB9AF7",
    "headerStart": "#292E42",
    "headerEnd": "#1A1B26",
    "headerText": "#7DCFFF",
    "bodyText": "#C0CAF5",
    "accentColor": "#E0AF68"
  },
  "chat": {
    "panelBackground": "#1A1B26",
    "borderColor": "#414868",
    "textColor": "#C0CAF5",
    "headerStart": "#15161E",
    "headerEnd": "#1A1B26",
    "headerText": "#F7768E",
    "messageAssistantBackground": "#24283B",
    "messageUserStart": "#F7768E",
    "messageUserEnd": "#BB9AF7",
    "inputBackground": "#15161E",
    "chatInputText": "#C0CAF5",
    "assistantMdHeading": "#7DCFFF",
    "assistantMdH1Underline": "#414868",
    "assistantMdParagraph": "#A9B1D6",
    "assistantMdStrong": "#9ECE6A",
    "assistantMdCodeBg": "#15161E",
    "assistantMdCodeText": "#E0AF68",
    "assistantMdCodeBorder": "#414868",
    "assistantMdPreBg": "#15161E",
    "assistantMdPreText": "#7AA2F7",
    "assistantMdPreBorder": "#414868",
    "assistantMdLink": "#BB9AF7",
    "assistantMdTableBorder": "#414868",
    "assistantMdThBg": "#24283B",
    "assistantMdThText": "#7DCFFF",
    "assistantMdEvenRowBg": "#1A1B26",
    "sendButtonStart": "#7DCFFF",
    "sendButtonEnd": "#7AA2F7"
  },
  "sourceFile": "tokyo_neon_night.json"
}'